
GET http://localhost:8080/users

POST http://localhost:8080/users
Content-Type: application/json
{
  "email": "test@example.com",
  "name": "Test User"
}

GET http://localhost:8080/users/1

PUT http://localhost:8080/users/1
Content-Type: application/json
{
  "email": "updated@example.com",
  "name": "Updated User"
}ы

DELETE http://localhost:8080/users/1
